name: VPS SSH via Ngrok (6 horas)

on: [push]

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 horas de timeout máximo

    steps:
      # Configuração básica do SSH
      - name: Gerar chaves SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/id_rsa

      - name: Mostrar chave privada
        run: |
          echo "----- INÍCIO DA CHAVE PRIVADA SSH (COLE NO TERMIUS) -----"
          cat ~/.ssh/id_rsa
          echo "----- FIM DA CHAVE PRIVADA -----"
          echo "Aguardando configuração do Ngrok..."

      - name: Instalar SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo service ssh start

      # Configuração do Ngrok (método direto sem apt)
      - name: Baixar e configurar Ngrok
        run: |
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar xzf ngrok-v3-stable-linux-amd64.tgz
          chmod +x ngrok
          ./ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
          echo "Ngrok configurado com sucesso!"
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

      - name: Iniciar túnel Ngrok
        run: |
          ./ngrok tcp 22 --log=stdout > ngrok.log &
          sleep 10
          URL=$(grep -oE "url=tcp://(.+)" ngrok.log | cut -d'/' -f3)
          echo "========================================"
          echo "✅ TÚNEL SSH ATIVO!"
          echo "🌐 ENDEREÇO: $URL"
          echo "👤 USUÁRIO: $(whoami)"
          echo "⏳ DURAÇÃO: 6 horas"
          echo "========================================"
          
          # Manter VPS ativa por 6 horas (21.600 segundos)
          sleep 21600

      - name: Verificar status (opcional)
        run: |
          echo "Status do Ngrok:"
          ./ngrok status
          echo "\nConexões SSH ativas:"
          sudo netstat -tulnp | grep sshd
